AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.6
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "Gemfile.lock"

Style/StringLiterals:
  EnforcedStyle: double_quotes
